
# Application properties
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/relations
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 3002