
# postgres sql connection
spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/posts
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create #create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
# Configuring the port for our server
server:
  port: 3001
